server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          #配置Git仓库的地址
          uri: ssh://git@git.dianpingoa.com/~lanxinyu/springcloud-config-repo.git
          username: lanxinyu
          password:
          search-paths:
          clone-on-start: true
  output:
    ansi:
      enabled: always
logging:
  level: debug
