server:
  port: 8030
spring:
  application:
    name: microservice-trace-zipkin-consumer-moive-client
  output:
    ansi:
      enabled: always
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0 #采样百分比，默认0.1即10%
logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: debug
    org.springframework.cloud.sleuth: debug
