FROM nginx
ADD http://172.18.162.206:8080/static/view/home.html /usr/share/nginx/html/index.html
#RUN echo 'Spring Cloud与Docker微服务实战' > /usr/share/nginx/html/index.html

# docker build -t nginx:my .
# my是tag （.）用于路径传递，表示当前路径
# docker run -d -p 91:80 nginx:my