server:
  port: 8020
spring:
  application:
    name: microservice-trace-zipkin-provider-user-client
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:meituan
    username: lansing
    password: lansing
  jpa:
    show-sql: true
  output:
    ansi:
      enabled: always
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0 #采样百分比，默认0.1即10%
logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: debug
    org.springframework.cloud.sleuth: debug
