server:
  port: 8061
spring:
  output:
    ansi:
      enabled: always
  application:
    name: microservice-config-server-eureka
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          username: lanxinyu
          password:
          uri: ssh://git@git.dianpingoa.com/~lanxinyu/springcloud-config-repo.git
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    register-with-eureka: true
  instance:
      prefer-ip-address: true