server:
  port: 8761
eureka:
  client:
    register-with-eureka: false #是否将自己注册到Eureka Server，默认为true。由于当前应用就是Eureka Server，故设置为false
    fetch-registry: false #是否哦从Eureka Server获取注册信息，默认为true。由于这是一个单节点的，不需要同步其他的ES节点数据，顾为false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  output:
    ansi:
      enabled: always
logging:
  level: debug