server:
  port: 8031
spring:
  output:
    ansi:
      enabled: always
  application:
    name: microservice-turbine
eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
  instance:
    prefer-ip-address: true
turbine:
  app-config: consumer-movie,microservice-consumer-movie-feign-hystrix-fallback-stream
  cluster-name-expression: "'default'"
